version: '3.7'
services:
  db:
    image: postgres:latest
    env_file: envs/dev.env
    ports:
      - 5432:5432
    volumes:
      - olympic:/var/lib/postgresql/data

  migration:
    build: .
    env_file: envs/dev.env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate;python manage.py seed_countries data/noc_regions.csv; python manage.py seed_athletes data/athlete_events.csv'

    volumes:
      - .:/code

    stdin_open: true
    tty: true

    depends_on:
      - db

  django:
    build: .
    container_name: dev-django
    env_file: envs/dev.env
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000"

    stdin_open: true
    tty: true

    ports:
      - 8000:8000

    volumes:
      - .:/code

    depends_on:
      - db
      - migration

volumes:
  olympic:
    external: true
