# Generated by Django 3.2.7 on 2021-10-02 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0003_auto_20211001_1839'),
        ('athletes', '0002_auto_20210930_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal_class', models.CharField(choices=[('G', 'Gold'), ('S', 'Silver'), ('B', 'Bronze')], max_length=1)),
                ('athlete', models.ManyToManyField(related_name='medals', to='athletes.Athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.event')),
            ],
        ),
    ]
