# Generated by Django 3.2.7 on 2021-09-30 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('noc', models.CharField(max_length=3)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='athletes', to='athletes.country'),
            preserve_default=False,
        ),
    ]
