# Generated by Django 3.2.7 on 2021-10-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_auto_20211005_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='noc',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
