# Generated by Django 3.2.7 on 2021-10-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0005_auto_20211005_0434'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['name'], name='athletes_at_name_dab051_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name', 'noc'], name='athletes_co_name_63bb75_idx'),
        ),
    ]
