# Generated by Django 3.2.7 on 2021-09-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='events',
            new_name='competitions',
        ),
    ]
