# Generated by Django 3.2.7 on 2021-10-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_year'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['name'], name='games_compe_name_c3d245_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['year', 'city'], name='games_game_year_fc0cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='sport',
            index=models.Index(fields=['name'], name='games_sport_name_347fda_idx'),
        ),
    ]
